name: Feature Request
description: Suggest an idea for dio_network_toolkit
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem does this solve? e.g. "I'm always frustrated when ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe the API or behavior you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds or alternative approaches you've thought of.
    validations:
      required: false
